version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      roslyn-and-test-packages:
        patterns:
          - "Microsoft.CodeAnalysis*"
          - "Microsoft.CodeAnalysis.Testing*"
          - "xunit*"
          - "coverlet*"
      other-nuget:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
